
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Mar 01 00:51:22 CST 2021
//----------------------------------------------------

package analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int div = 7;
  public static final int right_par = 3;
  public static final int id = 8;
  public static final int enteros = 9;
  public static final int left_par = 2;
  public static final int EOF = 0;
  public static final int menos = 4;
  public static final int error = 1;
  public static final int por = 6;
  public static final int combinado = 10;
  public static final int mas = 5;
}

